# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 200000
mask_before_softmax: False

runner: "parallel"

buffer_size: 30
best_buffer_size: 12
batch_size_run: 8
batch_size: 10
best_batch_size: 4

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 80

n_sum: 20 # number of sampling for exp_q (adjustable based on # of agents)
step: 5 #steps for tree back up diagram  (adjustable based on # of agents)
comm_channel: 2 # self.d = rnn_dim // comm_channel (adjustable based on # of agents)
cut_off: 0.0001 #cut_off factor for sigmoid annealing
coeff: 0.8  # policy annealing factor


lr: 0.0005
critic_lr: 0.0001
td_lambda: 0.8
tb_lambda: 0.9

# use qmix
mixing_embed_dim: 32

# use COMA
agent_output_type: "pi_logits"
learner: "offpg_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "offpg_smac"
